name: Build
on:
  push:
    branches: ["main"]
    paths: ["test.Dockerfile"]

jobs:
  docker:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        id: build-image
        run: docker build -t test:latest . -f test.Dockerfile